console.log("Hello, world!")
console.log("001_ono")
console.log("001_ono_reset")
console.log("001_ono_reset_2")
console.log("I've made a change and I wanna see the diff")
console.log("This is a new line added to see the diff")